- hosts: app
  name: Setup access
  gather_facts: no
  become: yes
  vars_files:
    - ./vars/access.yml
  remote_user: "{{ access_user }}"
  tags:
    - access
  roles:
    - sjb9774.access

- hosts: app
  remote_user: "{{ app_user }}"
  name: App setup
  tags:
    - app
  vars:
    - web_user: web-app

  roles:
    - role: sjb9774.epel
      tags:
        - toolchain
    - role: sjb9774.git
      tags:
        - toolchain
    - role: sjb9774.nginx
      tags:
        - toolchain
        - nginx
      vars:
        - https: true
    - role: sjb9774.certbot
      tags:
        - certbot
      vars:
        - certbot_email: stephen.biston@gmail.com
        - certbot_domain: "{{ nginx_server_name }}"
        - certbot_server: nginx
    - role: sjb9774.pip
      tags:
        - toolchain
        - pip
    - role: sjb9774.ruby
      tags:
        - ruby
        - toolchain
      remote_user: "{{ app_user }}"
    - role: sjb9774.gem
      tags:
        - ruby
        - gems
      remote_user: "{{ app_user }}"
    - role: sjb9774.gem-jekyll
      tags:
        - ruby
        - gems
    - role: sjb9774.web-app
      tags:
        - app-setup
      remote_user: "{{ app_user }}"
