---
- name: create jekyll build folders
  file:
    path: "/var/www/html/{{ web_user }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  become: yes

- name: create git folders
  file:
    path: "/srv/git/{{ web_user }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  become: yes

# for whatever reason this has to be done as sudo then chowned in the next step
- name: initialize empty git repo
  shell:
     cmd: "git init --bare /srv/git/{{ web_user }}/blog/.git"
  args:
     creates: "/srv/git/{{ web_user }}/blog/.git/HEAD"
  become: yes

- name: change owner of git repo
  file:
    path: "/srv/git/{{ web_user }}/blog/"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    recurse: yes
  become: yes

- name: change owner of nginx folders
  file:
    path: /usr/share/nginx
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    recurse: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes