---
- name: install policycoreutils
  package:
    name: policycoreutils-python
    state: present
  become: yes

- name: create jekyll build folders
  file:
    path: "{{ jekyll_build_path }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  become: yes

- name: create git folders
  file:
    path: "{{ repo_path }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  become: yes

# this has to be done as sudo then chowned in the next step otherwise ansible complains
- name: initialize empty git repo
  shell:
     cmd: "git init --bare {{ repo_path }}/{{ blog_name }}.git"
  args:
     creates: "{{ repo_path }}/{{ blog_name }}.git/HEAD"
  become: yes

- name: change owner of git repo
  file:
    path: "{{ repo_path }}/{{ blog_name }}.git"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    recurse: yes
  become: yes

- name: setup master post-deploy hook
  template:
    dest: "{{ repo_path }}/{{ blog_name }}.git/hooks/post-receive"
    src: templates/git-post-receive.j2
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    mode: "0754"

- name: create branch-specific post-receive scripts directory
  file:
    path: "{{ post_receive_branch_script_dir }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
  become: yes

- name: "setup post deploy hook for '{{ rebuild_branch }}' branch at {{ post_receive_branch_script_dir }}/{{ post_receive_branch_script_name }}"
  template:
    dest: "{{ post_receive_branch_script_dir }}/{{ post_receive_branch_script_name }}"
    src: templates/git-post-receive-for-branch.j2
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    mode: "0754"

- name: recreate nginx folder
  file:
    path: /usr/share/nginx/html
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
  become: yes

- name: create _site build folder
  file:
    path: "{{ jekyll_build_path }}/_site/"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_user }}"

- name: link jekyll build folder to nginx
  file:
    dest: "{{ nginx_server_root }}"
    src: "{{ jekyll_build_path }}/_site/"
    state: link
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    force: yes
  become: yes

# use for check later
- name: check SELinux context for site directory
  shell:
    cmd: "ls -Z {{ item }}"
  with_items:
    - "{{ jekyll_build_path }}/_site"
    - "{{ nginx_server_root }}"
  register: selinux_context
  changed_when: false

# sefcontext module seems very spotty, just using shell instead
- name: update SELinux context for site directory
  shell:
    cmd: "chcon -Rt httpd_sys_content_t {{ item }}"
  with_items:
    - "{{ jekyll_build_path }}/_site"
    - "{{ nginx_server_root }}"
  changed_when: false # TODO: implement a check here

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes
