---
- name: create jekyll build folders
  file:
    path: "{{ jekyll_build_path }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  become: yes

- name: create git folders
  file:
    path: "{{ repo_path }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  become: yes

# for whatever reason this has to be done as sudo then chowned in the next step
- name: initialize empty git repo
  shell:
     cmd: "git init --bare {{ repo_path }}/{{ blog_name }}/.git"
  args:
     creates: "{{ repo_path }}/{{ blog_name }}/.git/HEAD"
  become: yes

- name: change owner of git repo
  file:
    path: "{{ repo_path }}/{{ blog_name }}"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    recurse: yes
  become: yes

- name: update SELinux context for site directory
  sefcontext:
    target: "{{ jekyll_build_path }}/_site"
    setype: httpd_sys_content_t
    state: present

- name: change owner of nginx folders
  file:
    path: /usr/share/nginx
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    recurse: yes
  become: yes

- name: link jekyll build folder to nginx
  file:
    src: "/usr/share/nginx"
    dest: "{{ jekyll_build_path }}/_site"
    state: link
    owner: "{{ web_user }}"
    group: "{{ web_user }}"

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes